setwd("MAR")
library(parallel)
source("../report.R")
n.cores <- detectCores()

# Number of Monte Carlo tests
## Here we uploaded 20 generated datasets good for R up to 20.
## More data can be generated by GenData.R
R = 10
# Data for the following four combinations have been generated
# Data for other delta/rho combinations can be generated by GenData.R

# 1. MAR
delta <- 0
rho <- 0

# # 2. Weak Heckman-type MNAR
# delta <- 0
# rho <- 0.5
# 
# # 3. General MNAR
# delta <- 0.5
# rho <- 0
# 
# # 4. Strong general MNAR not shown in paper
# delta <- 2
# rho <- 0

n1 = c(750, 1500)
nmin <- 100

n3 = list()
for ( n in n1 )
{
  n3 = c(n3,list(c(n-2*nmin,rep(nmin,2))))
  n3 = c(n3,list(rep(n/3,3)))
}

n6 = list()
for ( n in n1 )
{
  n6 = c(n6,list(c(n-5*nmin,rep(nmin,5))))
  n6 = c(n6,list(rep(n/6,6)))
}




#######
# IMI #
#######

# K = 3
# R = 1000
M = 20
source("IMI/SimIMI.R")

ss <- rep(1:2, each = length(n3))
nn <- rep(n3, 2)
nc <- min(length(ss), n.cores)

resIMI3 <- mcmapply(FUN = SimIMI,
                    scen = ss,
                    n = nn,
                    MoreArgs = list(R = R, batch = 0, M = M),
                    mc.cores = nc,
                    SIMPLIFY = FALSE)
report(resIMI3)

# K = 6
# R = 1000
M = 20
source("IMI/SimIMI.R")
ss <- rep(1:2, each = length(n6))
nn <- rep(n6, 2)
nc <- min(length(ss), n.cores)

resIMI6 <- mcmapply(FUN = SimIMI,
                    scen = ss,
                    n = nn,
                    MoreArgs = list(R = R, batch = 0, M = M),
                    mc.cores = nc,
                    SIMPLIFY = FALSE)
report(resIMI6)


##########
# AVGMMI #
##########

# K = 3
# R = 1000
M = 20
source("AVGMMI/SimAVGMMI.R")

ss <- rep(1:2, each = length(n3))
nn <- rep(n3, 2)
nc <- min(length(ss), n.cores)

resAVGMMI3 <- mcmapply(FUN = SimAVGMMI,
                       scen = ss,
                       n = nn,
                       MoreArgs = list(R = R, batch = 0, M = M),
                       mc.cores = nc,
                       SIMPLIFY = FALSE)
report(resAVGMMI3)

# K = 6
# R = 1000
M = 20
source("AVGMMI/SimAVGMMI.R")
ss <- rep(1:2, each = length(n6))
nn <- rep(n6, 2)
nc <- min(length(ss), n.cores)

resAVGMMI6 <- mcmapply(FUN = SimAVGMMI,
                       scen = ss,
                       n = nn,
                       MoreArgs = list(R = R, batch = 0, M = M),
                       mc.cores = nc,
                       SIMPLIFY = FALSE)
report(resAVGMMI6)




# ##########
# # CSLMI #
# ##########
# 
# # K = 3
# # R = 1000
# M = 20
# source("CSLMI/SimCSLMI.R")
# 
# ss <- rep(1:2, each = length(n3))
# nn <- rep(n3, 2)
# nc <- min(length(ss), n.cores)
# 
# resCSLMI3 <- mcmapply(FUN = SimCSLMI,
#                       scen = ss,
#                       n = nn,
#                       MoreArgs = list(R = R, batch = 0, M = M),
#                       mc.cores = nc,
#                       SIMPLIFY = FALSE)
# report(resCSLMI3)
# 
# # K = 6
# # R = 1000
# M = 20
# source("CSLMI/SimCSLMI.R")
# 
# ss <- rep(1:2, each = length(n6))
# nn <- rep(n6, 2)
# nc <- min(length(ss), n.cores)
# 
# resCSLMI6 <- mcmapply(FUN = SimCSLMI,
#                       scen = ss,
#                       n = nn,
#                       MoreArgs = list(R = R, batch = 0, M = M),
#                       mc.cores = nc,
#                       SIMPLIFY = FALSE)
# report(resCSLMI6)


##############
# Aggregated #
##############

R <- 10
M <- 20
source("IMI/SimIMI.R")
ss <- rep(1:2, each = length(n1))
nn <- rep(n1, 2)
nc <- min(length(ss), n.cores)

resAGG <- mcmapply(FUN = SimIMI,
                   scen = ss,
                   n = nn,
                   MoreArgs = list(R = R, batch = 0, M = M),
                   mc.cores = nc,
                   SIMPLIFY = FALSE)
report(resAGG)
